# Generated by Django 3.0.6 on 2021-03-17 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('account_id', models.AutoField(primary_key=True, serialize=False)),
                ('account_number', models.IntegerField(blank=True, null=True)),
                ('account', models.CharField(blank=True, max_length=30, null=True)),
                ('labor_type_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'accounts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Functions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('function_id', models.CharField(blank=True, max_length=20, null=True)),
                ('function', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'functions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('resource_id', models.AutoField(primary_key=True, serialize=False)),
                ('resource', models.CharField(blank=True, max_length=80, null=True)),
                ('geo_id', models.IntegerField(blank=True, null=True)),
                ('active', models.IntegerField()),
            ],
            options={
                'db_table': 'resources',
                'managed': False,
            },
        ),
    ]
