# Generated by Django 3.0.5 on 2021-05-03 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaborAllocations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('function_id', models.IntegerField(blank=True, null=True)),
                ('component_id', models.IntegerField()),
                ('activity', models.CharField(blank=True, max_length=80, null=True)),
                ('quarter', models.CharField(blank=True, max_length=4, null=True)),
                ('lastupdated', models.DateTimeField(db_column='lastUpdated')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
            ],
            options={
                'db_table': 'labor_allocations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('project_num', models.AutoField(primary_key=True, serialize=False)),
                ('project', models.CharField(blank=True, max_length=80, null=True)),
            ],
            options={
                'db_table': 'projects',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='functions',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='resources',
            options={'managed': True},
        ),
    ]
